"use client";

import Link from "next/link";
import { useState } from "react";
import { Icon, Logo, Rating } from "../components";
import type { DashboardStatus } from "../dashboard-data";

type Role = "customer" | "farmer" | "admin";

const navByRole: Record<Role, { label: string; icon: string }[]> = {
  customer: [{ label: "Overview", icon: "home" }, { label: "My orders", icon: "package" }, { label: "Favorites", icon: "heart" }, { label: "Markets", icon: "storefront" }],
  farmer: [{ label: "Overview", icon: "home" }, { label: "Orders", icon: "package" }, { label: "Inventory", icon: "chart" }, { label: "Markets", icon: "storefront" }, { label: "Reviews", icon: "star" }],
  admin: [{ label: "Overview", icon: "home" }, { label: "Farmers", icon: "users" }, { label: "Customers", icon: "users" }, { label: "Markets", icon: "storefront" }, { label: "Categories", icon: "package" }, { label: "Reviews", icon: "star" }],
};
const roleLabels: Record<Role, string> = { customer: "Customer space", farmer: "Farmer workspace", admin: "Platform overview" };

export function DashboardShell({ role, name, initials, eyebrow, title, subtitle, children }: { role: Role; name: string; initials: string; eyebrow: string; title: string; subtitle: string; children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  return <div className={"dashboard-app dashboard-" + role}>
    <DashboardSidebar role={role} open={open} onClose={() => setOpen(false)} />
    {open && <button className="dashboard-sidebar-scrim" aria-label="Close navigation" onClick={() => setOpen(false)} />}
    <div className="dashboard-main-shell"><DashboardHeader name={name} initials={initials} onMenu={() => setOpen(true)} role={role} /><main className="dashboard-main"><div className="dashboard-container">
      <div className="dashboard-page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p></div><span className="dashboard-date"><Icon name="calendar" size={15} /> Saturday, 18 May 2025</span></div>
      {children}
    </div></main></div>
  </div>;
}

function DashboardSidebar({ role, open, onClose }: { role: Role; open: boolean; onClose: () => void }) {
  return <aside className={"dashboard-sidebar " + (open ? "is-open" : "")}>
    <div className="dashboard-sidebar-top"><Logo /><button className="dashboard-sidebar-close" onClick={onClose} aria-label="Close navigation"><Icon name="close" size={18} /></button></div>
    <div className="dashboard-role-label">{roleLabels[role]}</div>
    <nav className="dashboard-nav">{navByRole[role].map((item, index) => <Link className={"dashboard-nav-link " + (index === 0 ? "active" : "")} href={"/" + role + "/dashboard"} key={item.label}><Icon name={item.icon} size={18} /><span>{item.label}</span>{item.label === "Reviews" && role === "farmer" ? <b className="nav-count">2</b> : null}</Link>)}</nav>
    <div className="dashboard-sidebar-bottom"><Link className="dashboard-nav-link" href="/"><Icon name="external" size={18} /><span>Back to MarketLink</span></Link><Link className="dashboard-nav-link" href={"/" + role + "/dashboard"}><Icon name="settings" size={18} /><span>Settings</span></Link><div className="dashboard-sidebar-user"><span className="avatar avatar-small">{role === "customer" ? "AN" : role === "farmer" ? "GA" : "AD"}</span><div><strong>{role === "customer" ? "Ada Nwosu" : role === "farmer" ? "Green Acre Farms" : "MarketLink Admin"}</strong><small>{role === "customer" ? "Customer" : role === "farmer" ? "Verified farmer" : "Administrator"}</small></div><Icon name="more" size={17} /></div></div>
  </aside>;
}

function DashboardHeader({ name, initials, role, onMenu }: { name: string; initials: string; role: Role; onMenu: () => void }) {
  return <header className="dashboard-header"><div className="dashboard-container dashboard-header-inner"><button className="dashboard-menu-button" onClick={onMenu} aria-label="Open navigation"><Icon name="menu" size={21} /></button><div className="dashboard-mobile-brand"><Logo /></div><div className="dashboard-header-spacer" /><button className="dashboard-icon-button" aria-label="View notifications"><Icon name="bell" size={19} /><span className="notification-dot" /></button><div className="dashboard-user-menu"><span className="avatar">{initials}</span><div><strong>{name}</strong><small>{role === "admin" ? "Administrator" : role === "farmer" ? "Green Acre Farms" : "Customer"}</small></div><Icon name="chevron" size={15} /></div></div></header>;
}

export function StatGrid({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={"stat-grid " + className}>{children}</div>; }
export function StatCard({ label, value, detail, icon, trend, tone = "green" }: { label: string; value: string; detail?: string; icon: string; trend?: string; tone?: "green" | "orange" | "lilac" | "blue" }) { return <article className={"stat-card stat-card-" + tone}><span className="stat-icon"><Icon name={icon} size={18} /></span><div><p>{label}</p><strong>{value}</strong>{detail && <small>{detail}</small>}</div>{trend && <span className="stat-trend">{trend}</span>}</article>; }
export function SectionHeader({ eyebrow, title, action = "View all" }: { eyebrow?: string; title: string; action?: string | null }) { return <div className="dashboard-section-header"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2></div>{action && <button className="dashboard-link-button">{action}<Icon name="arrow" size={15} /></button>}</div>; }
export function StatusBadge({ status }: { status: DashboardStatus | string }) { const tone = status.includes("Ready") || status === "Approved" || status === "Available" || status === "Completed" || status === "Active" || status === "Published" || status === "Selling Today" ? "green" : status.includes("Low") || status === "Pending" || status === "Placed" || status === "Needs reply" || status === "Quiet this week" ? "amber" : status === "Rejected" || status === "Cancelled" || status === "Declined" || status === "Sold Out" || status === "Suspended" ? "red" : "neutral"; return <span className={"dashboard-status status-" + tone}><i />{status}</span>; }
export function QuickActions({ items }: { items: string[] }) { return <div className="quick-actions">{items.map((item, index) => <button className="quick-action" key={item}><span><Icon name={index === 0 ? "plus" : index === 1 ? "package" : index === 2 ? "chart" : "calendar"} size={17} /></span>{item}<Icon name="arrow" size={15} /></button>)}</div>; }

export function OrderCard({ order }: { order: { id: string; farmer: string; farmerInitials: string; market: string; items: string; amount: string; date: string; time: string; status: DashboardStatus } }) { return <article className="order-card"><div className="order-card-top"><span className="avatar avatar-farm">{order.farmerInitials}</span><div className="order-card-title"><div><strong>{order.farmer}</strong><small>{order.id}</small></div><StatusBadge status={order.status} /></div></div><p className="order-items">{order.items}</p><div className="order-card-meta"><span><Icon name="storefront" size={14} />{order.market}</span><span><Icon name="calendar" size={14} />{order.date} · {order.time}</span><strong>{order.amount}</strong></div></article>; }
export function PickupCard({ order }: { order: { id: string; farmer: string; farmerInitials: string; market: string; time: string; date: string; status: DashboardStatus } }) { return <article className="pickup-card"><div className="pickup-card-copy"><div className="pickup-card-top"><span className="pickup-kicker"><Icon name="truck" size={14} /> UPCOMING PICKUP</span><StatusBadge status={order.status} /></div><h3>{order.farmer}</h3><p>{order.market}</p><div className="pickup-details"><span><small>Date</small><strong>{order.date}</strong></span><span><small>Pickup time</small><strong>{order.time}</strong></span></div></div><div className="pickup-code"><small>PICKUP CODE</small><strong>ML-482193</strong><span>Show this code at the farmer&apos;s stall</span></div></article>; }
export function FarmerCardSmall({ farmer }: { farmer: { name: string; speciality: string; markets: string; rating: number; reviews: number; sellingToday: boolean; image: string; accent: string } }) { return <article className="dashboard-farmer-card"><div className="dashboard-image" style={{ backgroundImage: "url(" + farmer.image + ")" }}>{farmer.sellingToday && <span className="selling-pill"><i /> Selling today</span>}</div><div className="dashboard-farmer-info"><div><strong>{farmer.name}</strong><small>{farmer.speciality}</small></div><span className="round-initial" style={{ background: farmer.accent }}>{farmer.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</span><p><Icon name="pin" size={14} />{farmer.markets.split(" · ")[0]}</p><Rating value={farmer.rating} reviews={farmer.reviews} /></div></article>; }
export function DashboardProductCard({ product }: { product: { name: string; farmer: string; market: string; price: string; unit: string; availability: string; status: string; image: string } }) { return <article className="dashboard-product-card"><div className="dashboard-product-image dashboard-image" style={{ backgroundImage: "url(" + product.image + ")" }}><StatusBadge status={product.status === "low" ? "Low Stock" : product.status === "sold" ? "Sold Out" : "Available"} /></div><div className="dashboard-product-info"><strong>{product.name}</strong><small>{product.farmer} · {product.market.split(" ")[0]}</small><div><span>{product.price} <em>{product.unit}</em></span><small>{product.availability}</small></div></div></article>; }
export function MarketCardSmall({ market, meta }: { market: { name: string; area: string; days: string; hours: string; open: boolean; image: string }; meta?: string }) { return <article className="dashboard-market-card"><div className="dashboard-market-image dashboard-image" style={{ backgroundImage: "url(" + market.image + ")" }}><StatusBadge status={market.open ? "Selling Today" : "Not Selling Today"} /></div><div className="dashboard-market-info"><strong>{market.name}</strong><small><Icon name="pin" size={13} />{market.area}</small><div><span><Icon name="calendar" size={13} />{market.days}</span><span>{meta || market.hours}</span></div></div></article>; }
export function NotificationItem({ item }: { item: { title: string; text: string; time: string; tone: string } }) { return <article className="notification-item"><span className={"notification-symbol notification-" + item.tone}><Icon name={item.tone === "green" ? "check" : item.tone === "orange" ? "bell" : "calendar"} size={15} /></span><div><strong>{item.title}</strong><p>{item.text}</p><small>{item.time}</small></div></article>; }

export function PickupTable({ orders }: { orders: { customer: string; initials: string; id: string; pickup: string; items: number; status: DashboardStatus }[] }) { return <div className="dashboard-table-wrap"><table className="dashboard-table"><thead><tr><th>Customer</th><th>Order</th><th>Pickup time</th><th>Items</th><th>Status</th><th /></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><span className="table-person"><span className="avatar avatar-small">{order.initials}</span><strong>{order.customer}</strong></span></td><td className="table-muted">{order.id}</td><td>{order.pickup}</td><td>{order.items} items</td><td><StatusBadge status={order.status} /></td><td><button className="table-more" aria-label={"More options for " + order.id}><Icon name="more" size={17} /></button></td></tr>)}</tbody></table></div>; }
export function InventoryTable({ items }: { items: { name: string; stock: number; reserved: number; sold: number; available: number; status: DashboardStatus; accent: string }[] }) { return <div className="dashboard-table-wrap"><table className="dashboard-table inventory-table"><thead><tr><th>Product</th><th>Stock</th><th>Reserved</th><th>Sold</th><th>Available</th><th>Status</th></tr></thead><tbody>{items.map((item) => <tr key={item.name}><td><span className="inventory-product"><i style={{ background: item.accent }} /> <strong>{item.name}</strong></span></td><td>{item.stock}</td><td>{item.reserved}</td><td>{item.sold}</td><td><span className="available-stock"><b>{item.available}</b><i><em style={{ width: Math.max(item.available / item.stock * 100, 4) + "%" }} /></i></span></td><td><StatusBadge status={item.status} /></td></tr>)}</tbody></table></div>; }
export function ReviewCard({ review }: { review: { name: string; initials?: string; rating: number; text: string; date?: string; context?: string; flag?: string } }) { return <article className="review-card"><div className="review-card-top"><span className="avatar avatar-small">{review.initials || review.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span><div><strong>{review.name}</strong><small>{review.context || review.date}</small></div><div className="review-stars">{Array.from({ length: 5 }).map((_, index) => <Icon name="star" size={13} key={index} />)}</div></div><p>&ldquo;{review.text}&rdquo;</p>{review.flag ? <StatusBadge status={review.flag} /> : <small className="review-date">{review.date}</small>}</article>; }
export function ApprovalTable({ approvals }: { approvals: { name: string; owner: string; email: string; joined: string; category: string; initials: string; accent: string }[] }) { return <div className="dashboard-table-wrap"><table className="dashboard-table approval-table"><thead><tr><th>Business</th><th>Owner & contact</th><th>Category</th><th>Joined</th><th>Status</th><th /></tr></thead><tbody>{approvals.map((approval) => <tr key={approval.name}><td><span className="table-person"><span className="avatar avatar-small" style={{ background: approval.accent }}>{approval.initials}</span><strong>{approval.name}</strong></span></td><td><span className="contact-cell"><strong>{approval.owner}</strong><small>{approval.email}</small></span></td><td>{approval.category}</td><td className="table-muted">{approval.joined}</td><td><StatusBadge status="Pending" /></td><td><span className="approval-actions"><button>Review</button><button className="approve-button">Approve</button><button className="reject-button">Reject</button></span></td></tr>)}</tbody></table></div>; }
export function PlatformOrderTable({ orders }: { orders: { id: string; customer: string; farmer: string; market: string; amount: string; status: DashboardStatus }[] }) { return <div className="dashboard-table-wrap"><table className="dashboard-table"><thead><tr><th>Order</th><th>Customer</th><th>Farmer</th><th>Market</th><th>Amount</th><th>Status</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><strong>{order.id}</strong></td><td>{order.customer}</td><td>{order.farmer}</td><td className="table-muted">{order.market}</td><td><strong>{order.amount}</strong></td><td><StatusBadge status={order.status} /></td></tr>)}</tbody></table></div>; }
